name: Exportar Godot a APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  export-android:
    runs-on: ubuntu-latest
    name: Compilar juego para Android
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Compilar con Godot
        uses: firebelley/godot-export@v5.2.0
        with:
          godot: https://github.com/godotengine/godot/releases/download/4.2.1-stable/Godot_v4.2.1-stable_linux.x86_64.zip
          godot_export_templates: https://github.com/godotengine/godot/releases/download/4.2.1-stable/Godot_v4.2.1-stable_export_templates.tpz
          relative_project_path: ''
